spring:
  application:
    name: security-pwd-credentials
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.0.102
    port: 6379
    database: 0
    password: 123456
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        max-idle: 8
        min-idle: 0

  datasource:
    url: jdbc:mysql://192.168.0.102:3306/oauth2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5

dubbo:
  scan:
    base-packages:
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://127.0.0.1:8848

server:
  port: 9001

oauth2:
  client_id: client
  client_secret: secret
  grant_type: password